--1.Database RECOVERY MODE full
--2.Database full backup
--3.Log file SHRINK
USE master
GO
IF DB_ID('TestDB') IS NOT NULL DROP DATABASE TestDB
GO 
CREATE DATABASE TestDB
GO
USE TestDB
GO
CREATE TABLE dbo.Table1(
	ID INT IDENTITY,
	TEN VARCHAR(32)
)
GO
INSERT INTO dbo.Table1(TEN)
SELECT A = 'Maysam A' UNION ALL
SELECT B = 'Maysam B' UNION ALL
SELECT C = 'Maysam C'
GO
--full backup
BACKUP DATABASE TestDB TO DISK = 'E:\SQLData\Backup\TestDB.bak' WITH INIT

INSERT INTO dbo.Table1(TEN)
SELECT 'Maysam D' UNION ALL
SELECT 'Maysam E'

BACKUP DATABASE TestDB TO DISK = 'E:\SQLData\Backup\TestDB_Diff.bak' WITH DIFFERENTIAL

DELETE FROM dbo.Table1

ALTER DATABASE TestDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE

SELECT GETDATE()

USE master
GO
RESTORE DATABASE TestDB FROM DISK = 'E:\SQLData\Backup\TestDB.bak' WITH NORECOVERY
RESTORE DATABASE TestDB FROM DISK = 'E:\SQLData\Backup\TestDB.trn' WITH STOPAT = '2017-08-02 15:16:05'

USE TestDB
SELECT * FROM dbo.Table1

ALTER DATABASE TestDB SET MULTI_USER
