CREATE DATABASE StudentDB
GO
USE StudentDB
GO 
CREATE TABLE StudentDB.dbo.Class (
	ClassID INT PRIMARY KEY NOT NULL,
	ClassName VARCHAR(32)
)
GO
CREATE TABLE StudentDB.dbo.Student(
	StudentID INT PRIMARY KEY NOT NULL,
	Name VARCHAR(64),
	Address VARCHAR(32),
	ClassID INT,
	CONSTRAINT FK_ClassID FOREIGN KEY (ClassID) REFERENCES Class(ClassID)
)
GO
SELECT * FROM StudentDB.dbo.Class
GO
SELECT * FROM StudentDB.dbo.Student

INSERT INTO Class VALUES(1,'12A1')
INSERT INTO Class VALUES(2,'12A2')
INSERT INTO Class VALUES(3,'12Y')


INSERT INTO Student
VALUES(
1,'Maysam Solaymani','Iran',1
)

INSERT INTO Student
VALUES(
2,'Bil Gates','USA',3)

INSERT INTO Student
VALUES(
3,'CZ','China',2
)

INSERT INTO Student
VALUES(
4,'Tom Hanks','USA',2
)
